openapi: 3.0.0
# Added by Tunde Ajagbe
servers:
 # - description: Warehouse Inventory Management System
  #  url: https://virtserver.swaggerhub.com/TundeMercy/warehouse-manager-doc/1.0.0
  - description: Local Machine
    url: localhost:5002
info:
  description: This is warehouse-manager API
  version: "1.0.0"
  title: Warehouse Manager API
  contact:
    email: tundeajagbea@gmail.com
  license:
    name: Tunde 2.0
    url: 'https://github.com/TundeMercy/warehouse-manager-api'
tags:
  - name: admin
    description: Secured Admin-only calls
  - name: mall Attendant(User)
    description: Secured Attendant-only calls

paths:
  /products:
    parameters:
        - in: header
          name: role
          description: User's role
          required: true
          schema:
           type: string
           enum: [admin,attendant,otherUsers]
    post:
      tags:
        - admin
      summary: Adds a product
      operationId: addInventory
      description: Adds a new product to the system
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductModelR'
          description: OK. Product returned
        '400':
          description: Bad request. Invalid input, object invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400error'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProductModel'
        description: Product to add
    get:
      tags:
        - admin
        - mall Attendant(User)
      summary: gets all products record from the system
      operationId: getAllProducts
      description: |
        This endpoint returns all products record to an authorized user.
      responses:
        '200':
          description: Access is granted products record is returned.
          content:
            application/json:
              schema:
                  items:
                    $ref: '#/components/schemas/ProductModelR'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'

  /products/{id}:
    parameters:
        - in: header
          name: role
          description: User's role
          required: true
          schema:
           type: string
           enum: [admin,attendant,otherUsers]
    get:
      summary: Gets product by id
      operationId: getProductbyId
      description: |
        By passing in the appropriate id, you can search for
        available product in the system
      parameters:
        - in: path
          name: id
          description:  Numeric ID of the product to fetch
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: search result match criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductModelR'
        '404':
          description: No product match the id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404error'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
      tags:
        - admin
        - mall Attendant(User)
    put:
      tags:
        - admin
      summary: Update product by id
      operationId: editProductsbyId
      description: |
        By passing in the appropriate id, you can edit a product in the system
      parameters:
        - in: path
          name: id
          description:  ID of the product to update
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProductModelU'
        description: Properties to Update
      responses:
        '200':
          description: succesfully edited the product. Returns the edited product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductModelR'
        '404':
          description: No product match the id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404error'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
        '400':
          description: Bad request. Invalid input, object invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400error'
  /sales:
    parameters:
        - in: header
          name: role
          description: User's role
          required: true
          schema:
           type: string
           enum: [admin,attendant,otherUsers]
    get:
      tags:
        - admin
        - mall Attendant(User)
      summary: gets all sales record from the system
      operationId: getAllSales
      description: |
        This endpoint returns all sales record to an authorized user.
      responses:
        '200':
          description: Access is granted all sale record is returned.
          content:
            application/json:
              schema:
                items:
                 $ref: '#/components/schemas/SaleModelR'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
    post:
      tags:
        - mall Attendant(User)
      summary: adds a new sales record
      operationId: addSale
      description: |
        Adds a new sale record to the system. Modifies the product sold in product collection by deducting from its quantity property. Also modifies user collection by adding to the user sales property.  Returns the newly added sale
      responses:
        '200':
          description: OK. Sale created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleModelR'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
        '400':
          description: Bad request. Invalid input, object invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaleModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SaleModel'
        description: Sales Model to add
    
  /sales/{id}:
    parameters:
        - in: header
          name: role
          description: User's role
          required: true
          schema:
           type: string
           enum: [admin,attendant,otherUsers]
    get:
      summary: gets sale by id
      operationId: getSalebyId
      description: |
        By passing in the appropriate id, you can search for
        available product in the system
      parameters:
        - in: path
          name: id
          description:  ID of the sale to fetch
          required: true
          schema:
            type: number
      responses:
        '200':
          description: search result match criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleModelR'
        '404':
          description: No sale match the id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404error'
        '401':
          description: 'Access denied'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
      tags:
        - admin
        - mall Attendant(User)
  /users:
    parameters:
        - in: header
          name: role
          description: User's role
          required: true
          schema:
           type: string
           enum: [admin,attendant,otherUsers]
    get:
      tags:
        - admin
        - mall Attendant(User)
      summary: gets all mall attendant(users) record from the system
      operationId: getAllUsers
      description: |
        This endpoint returns all users record to an authorized user.
      responses:
        '200':
          description: Access is granted and all sale record is returned.
          content:
            application/json:
              schema:
                items:
                 $ref: '#/components/schemas/UserModelR'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
    post:
      tags:
        - admin
      summary: adds a new mall attendant(user)
      operationId: addUser
      description: Adds a new mall attendant to the system
      responses:
        '201':
          description: user created and the new user is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModelR'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
        '400':
          description: Bad request. Invalid input, object invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserModel'
        description: Mall attendant(User) to add
  /users/{id}:
    parameters:
        - in: header
          name: role
          description: User's role
          required: true
          schema:
           type: string
           enum: [admin,attendant,otherUsers]
    get:
      summary: gets user by id
      operationId: getUserbyId
      description: |
        By passing in the appropriate id, you can search for
        a particular user in the system
      parameters:
        - in: path
          name: id
          description:  ID of the mall attendant to fetch
          required: true
          schema:
            type: number
      responses:
        '200':
          description: search result match criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModelR'
        '404':
          description: No mall attendant match the id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404error'
        '401':
          description: Access denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401error'
      tags:
        - admin
        - mall Attendant(User)
    
    
components:
  schemas:
    ProductModelR:
      type: object
      properties:
        id:
          type: number
          example: 5
        name:
          type: string
          example: tomatoes
        category:
          type: string
          example: vegetables
        price:
          type: string
          example: $10.99
        quantity:
          type: number
          example: 10
        description:
          type: string
          example: A very nice crop top
        image_url:
          type: string
          format: url
          example: 'https://dummyimage.com/img1'
    ProductModel:
      type: object
      required:
        - name
        - category
        - price
        - quantity
      properties:
        name:
          type: string
          example: tomatoes
        category:
          type: string
          example: vegetables
        price:
          type: string
          example: $10.99
        quantity:
          type: number
          example: 10
        description:
          type: string
          example: A very nice crop top
        image_url:
          type: string
          format: url
          example: 'https://dummyimage.com/img1'
    ProductModelU:
      type: object
      properties:
        name:
          type: string
          example: tomatoes
        category:
          type: string
          example: vegetables
        price:
          type: string
          example: $9.99
        quantity:
          type: number
          example: 50
        description:
          type: string
          example: A very nice crop top
        image_url:
          type: string
          format: url
          example: 'https://dummyimage.com/img1'
    UserModel:
      type: object
      required:
        - first_name
        - email
        - role
        - sale
      properties:
        firstname:
          type: string
          example: Tunde
        email:
          type: string
          example: 'tunde@gmail.com'
        mobile_number:
          type: number
          example: 8106772233
        sale:
          type: number
          example: 24
        role:
          type: string
          example: attendant
        image_url:
          type: string
          format: url
          example: 'http://dummyimage.com/img43455'
    UserModelR:
      type: object
      properties:
        id:
          type: number
          example: 1
        firstname:
          type: string
          example: Tunde
        email:
          type: string
          example: 'tunde@gmail.com'
        mobile_number:
          type: number
          example: 8106772233
        sale:
          type: number
          example: 24
        role:
          type: string
          example: attendant
        image_url:
          type: string
          format: url
          example: 'http://dummyimage.com/img43455'
    SaleModel:
      type: object
      required:
        - seller_id
        - unit_price
        - quantity_sold
      properties:
        seller_id:
          type: number
          example: 1
        unit_price:
          type: string
          example: $50.50
        quantity_sold:
          type: number
          example: 15
    SaleModelR:
      type: object
      properties:
        product_id:
          type: number
          example: 1
        seller_id:
          type: number
          example: 1
        unit_price:
          type: string
          example: $50.50
        quantity_sold:
          type: number
          example: 15
    404error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: number
              example: 404
            message:
              type: string
              example: 'User not found'
    401error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: number
              example: 401
            message:
              type: string
              example: 'You are not authorized to make this request'
    400error:
      type: string
      example: "Some unknown property is not allowed"
        